authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CaNNOLeS = "5a1c9e79-9c58-5ec0-afc4-3298fdea2875"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DCISolver = "bee2e536-65f6-11e9-3844-e5bb4c9c55c9"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSOSolvers = "10dff2fc-5484-5881-a0e0-c90441020f8a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
ManualNLPModels = "30dfa513-9b2f-4fb3-9796-781eabac1617"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Percival = "01435c0c-c90d-11e9-3788-63660f8fbccc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SolverBenchmark = "581a75fa-a23a-52d0-a590-d6201de2218a"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"

[compat]
ADNLPModels = "0.3"
BenchmarkTools = "1"
CaNNOLeS = "0.5"
Colors = "0.12"
FFTW = "1"
Franklin = "0.10"
Ipopt = "0.7"
JSON = "0.21"
JSOSolvers = "0.7"
JuMP = "0.21"
LinearOperators = "2"
Literate = "2"
ManualNLPModels = "0.1"
NLPModels = "0.17"
NLPModelsIpopt = "0.7"
NLPModelsJuMP = "0.8"
NodeJS = "1"
Percival = "0.4, 0.5"
Plots = "1"
SolverBenchmark = "0.4"
SolverCore = "0.2"
SolverTools = "0.7"
