authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSOSolvers = "10dff2fc-5484-5881-a0e0-c90441020f8a"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SolverBenchmark = "581a75fa-a23a-52d0-a590-d6201de2218a"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"
